server:
  port: 8084

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/userDB
    username: localeconnect
    password: lssa2324app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: localeconnect.team@gmail.com
    password: dosa yoeh rbtc nzvb
    properties.mail.smtp:
       auth: true
       starttls.enable: true

jwt:
  secret: 6EB8F0418D5AE34CA2C60A1446F466F2C50074D7762DD6F969C551DB011411C8
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
