server:
  port: 8084

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: localeconnect
    password: lssa2324app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: localeconnect.team@gmail.com
    password: dosa yoeh rbtc nzvb
    properties.mail.smtp:
       auth: true
       starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka