server:
  port: 8084

spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: 'localeconnect'
    password: 'lssa2324app'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka