server:
  port: 7001

spring:
  application:
    name: meetup
  datasource:
    url: jdbc:postgresql://localhost:5432/meetup-DB
    username: localeconnect
    password: lssa2324app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
