server:
  port: 8081

spring:
  application:
    name: feed

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/feedDB
    username: localeconnect
    password: lssa2324app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    redis:
#      host: redis-service
#      port: 6379
#      username: guest
#      password: guest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
