server:
  port: 5005

spring:
  application:
    name: gcp-service

gcs-resource-bucket: localeconnect_bucket

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


gcp:
  credentials:
    path: ${GCP_CONFIG:C:\Users\MahaMarhag\IdeaProjects\localeconnect\LocaleConnectBackend\gcloud.json}