
#To access a route use the link: localhost:8080/path-to-service
# Example: eureka -> localhost:8080/eureka/web
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed
        - id: itinerary
          uri: lb://itinerary
          predicates:
            - Path=/api/itinerary
        - id: meetup-service
          uri: lb://meetup-service
          predicates:
             - Path=/api/meetup
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trip
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**



eureka:
 client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty.http.client: DEBUG

