version: "3.8"

services:

  postgres-service:
    image: postgres:latest
    container_name: postgres-service
    environment:
      POSTGRES_USER: localeconnect
      POSTGRES_PASSWORD: lssa2324app
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  api-gateway:
    image: georgemaged/api-gateway
    pull_policy: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka
    ports:
      - 8080:8080
    restart: always

  chat-service:
    image: georgemaged/chat-service:latest
    pull_policy: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka

  meetup-service:
    image: georgemaged/meetup-service:latest
    pull_policy: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka
      - DB_HOST=postgres-service

  user-service:
    image: georgemaged/user-service:latest
    pull_policy: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka
      - DB_HOST=postgres-service

  itinerary-service:
    image: georgemaged/itinerary-service:latest
    pull_policy: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka
      - DB_HOST=postgres-service

  feed-service:
    image: georgemaged/feed-service:latest
    pull_policy: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka
      - DB_HOST=postgres-service

  discovery-server:
    image: georgemaged/discovery-server
    pull_policy: always
    ports:
      - '8761:8761'


volumes:
  postgres:
  pgadmin: