import {Component} from '@angular/core';
import {MatDialogRef} from '@angular/material/dialog';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Itinerary, Tag} from "../../../model/itinerary";
import {ItineraryService} from "../../../service/itinerary.service";
import * as DataHelper from 'src/app/helper/DataHelper';
@Component({
  selector: 'app-itinerary-dialog',
  templateUrl: 'itinerary-dialog.component.html',
  styleUrls: ['./itinerary-dialog.component.scss']

})
export class ItineraryDialogComponent {
  itineraryForm: FormGroup;
  images: string[] = [];
  tagOptions :Tag[]= Object.values(Tag).filter(key => isNaN(Number(key))) as Tag[];


  constructor(
    public dialogRef: MatDialogRef<ItineraryDialogComponent>,
    private formBuilder: FormBuilder, private itineraryService: ItineraryService
  ) {
    this.itineraryForm = this.formBuilder.group({
      name: ['', Validators.required],
      description: ['', Validators.required],
      numberOfDays: ['1', [Validators.required, Validators.min(1)]],
      tags: [''],
      placesToVisit: ['', Validators.required],
      dailyActivities: [''],
      image: ['']
    });
  }

  onNoClick(): void {
    this.dialogRef.close(null);
  }

  onSubmit(): void {
    if (this.itineraryForm.valid) {
      const formData = this.itineraryForm.value;
      formData.placesToVisit = DataHelper.dataToList(formData.placesToVisit);
      formData.dailyActivities = DataHelper.dataToList(formData.dailyActivities);



      const itinerary: Itinerary = {
        id: 0, // generated by the backend
        //TODO: get from the user
        userId: 0,//generated by the backend
        name: formData.name,
        username: '',
        description: formData.description,
        numberOfDays: formData.numberOfDays,
        tags:formData.tags,
        mappedTags:formData.tags,
        placesToVisit: formData.placesToVisit,
        dailyActivities: formData.dailyActivities,
        expand: false,
        imageUrls: formData.image,
        rating: 0
      };

      this.itineraryService.changeItinerary(itinerary);
      this.dialogRef.close();
    }


  }

  onFileSelected(event: any) {
    const files = event.target.files;
    if (files) {
      for (let file of files) {
        const reader = new FileReader();
        reader.onload = (e: any) => {
          this.images.push(e.target.result);
        };
        reader.readAsDataURL(file);
      }
    }
  }


}
